// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-Pjav6kRcyHo7bseCK0K_lAmkSHzCgic',
    appId: '1:283019933341:web:9d94b3ca68d45fb89b4674',
    messagingSenderId: '283019933341',
    projectId: 'petflix-74e35',
    authDomain: 'petflix-74e35.firebaseapp.com',
    storageBucket: 'petflix-74e35.firebasestorage.app',
    measurementId: 'G-QFTC44CR29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJe2yVpHtLmOUvHNtKXazehlR4JKOdI1s',
    appId: '1:283019933341:android:c10eef75280ea46b9b4674',
    messagingSenderId: '283019933341',
    projectId: 'petflix-74e35',
    storageBucket: 'petflix-74e35.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-Pjav6kRcyHo7bseCK0K_lAmkSHzCgic',
    appId: '1:283019933341:web:e2d6ec43c7144fbe9b4674',
    messagingSenderId: '283019933341',
    projectId: 'petflix-74e35',
    authDomain: 'petflix-74e35.firebaseapp.com',
    storageBucket: 'petflix-74e35.firebasestorage.app',
    measurementId: 'G-9D78ND2XDT',
  );
}
